@extends('layouts.app')
@section('title','Edit Produk')
@section('content')
<h1 class="text-xl font-bold mb-4">Edit {{ $product->name }}</h1>
<form method="POST" action="{{ route('products.update',$product) }}" class="bg-white rounded-2xl border p-4 sm:p-6 space-y-4 max-w-2xl">@csrf @method('PUT')
<div><label class="text-sm font-medium">Nama *</label><input name="name" value="{{ $product->name }}" required class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label class="text-sm">SKU *</label><input name="sku" value="{{ $product->sku }}" required class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div><div><label class="text-sm">Barcode</label><input name="barcode" value="{{ $product->barcode }}" class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div></div>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label class="text-sm">Kategori *</label><select name="category_id" required class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm bg-white">@foreach($categories as $c)<option value="{{ $c->id }}" @selected($product->category_id==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div><label class="text-sm">Tipe *</label><select name="type" required class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm bg-white"><option value="product" @selected($product->type=='product')>Product</option><option value="service" @selected($product->type=='service')>Service</option></select></div></div>
<div class="grid grid-cols-1 sm:grid-cols-3 gap-4"><div><label class="text-sm">Harga *</label><input name="price" type="number" value="{{ $product->price }}" required class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div><div><label class="text-sm">HPP</label><input name="cost" type="number" value="{{ $product->cost }}" class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div><div><label class="text-sm">Unit *</label><select name="unit" class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm bg-white"><option value="pcs" @selected($product->unit=='pcs')>pcs</option><option value="kg" @selected($product->unit=='kg')>kg</option><option value="meter" @selected($product->unit=='meter')>meter</option><option value="liter" @selected($product->unit=='liter')>liter</option></select></div></div>
<div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label class="text-sm">Status</label><select name="status" class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm bg-white"><option value="active" @selected($product->status=='active')>active</option><option value="inactive" @selected($product->status=='inactive')>inactive</option></select></div><div><label class="text-sm">Deskripsi</label><input name="description" value="{{ $product->description }}" class="mt-1 w-full border border-slate-200 rounded-xl px-3 py-3 text-sm"></div></div>
<div class="flex gap-2 pt-2"><button class="flex-1 sm:flex-none bg-indigo-600 text-white px-6 py-3 rounded-xl font-semibold">Update</button><a href="{{ route('products.index') }}" class="px-6 py-3 text-sm text-slate-500">Batal</a></div>
</form>
@endsection
